#!/usr/bin/env node
/**
 * First-run setup after cloning the repo.
 *   npm run setup
 * Opens the built extension folder and Chrome when passed --open.
 */
import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const openAfter = process.argv.includes('--open');
const PLACEHOLDER_TOKEN = 'generate-a-long-random-token';

function fail(message) {
  console.error(`\n${message}\n`);
  process.exit(1);
}

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: root,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });
  if (result.error) fail(`${command} could not be started: ${result.error.message}`);
  return result.status ?? 1;
}

function parseEnv(text) {
  const values = {};
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    values[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return values;
}

function isReal(value, placeholders) {
  if (!value) return false;
  return !placeholders.some((placeholder) => value.includes(placeholder));
}

const nodeMajor = Number(process.versions.node.split('.')[0]);
if (!Number.isFinite(nodeMajor) || nodeMajor < 20) {
  fail(
    `This project needs Node.js 20 or newer. You have ${process.version}.\n` +
      'Install the current LTS from https://nodejs.org and run this again.',
  );
}

if (!existsSync(join(root, 'node_modules', 'typescript'))) {
  console.log('\nInstalling dependencies (first time only)…\n');
  const status = existsSync(join(root, 'package-lock.json'))
    ? run('npm', ['ci'])
    : run('npm', ['install']);
  if (status !== 0) fail('Dependency install failed. Fix the error above, then run npm run setup again.');
}

const envPath = join(root, '.env');
const examplePath = join(root, '.env.example');
if (!existsSync(envPath)) {
  if (!existsSync(examplePath)) fail('Missing .env.example');
  writeFileSync(envPath, readFileSync(examplePath, 'utf8'));
  console.log('Created .env from .env.example');
}

let envText = readFileSync(envPath, 'utf8');
let env = parseEnv(envText);
const devVarsPath = join(root, 'workers', 'tracker', '.dev.vars');
const existingDev = existsSync(devVarsPath) ? parseEnv(readFileSync(devVarsPath, 'utf8')) : null;

if (!isReal(env.PERSONAL_API_TOKEN, [PLACEHOLDER_TOKEN])) {
  const token = isReal(existingDev?.PERSONAL_API_TOKEN, [PLACEHOLDER_TOKEN])
    ? existingDev.PERSONAL_API_TOKEN
    : randomBytes(32).toString('base64url');
  if (envText.includes(`PERSONAL_API_TOKEN=${PLACEHOLDER_TOKEN}`)) {
    envText = envText.replace(`PERSONAL_API_TOKEN=${PLACEHOLDER_TOKEN}`, `PERSONAL_API_TOKEN=${token}`);
  } else if (envText.includes('PERSONAL_API_TOKEN=')) {
    envText = envText.replace(/PERSONAL_API_TOKEN=.*/g, `PERSONAL_API_TOKEN=${token}`);
  } else {
    envText += `\nPERSONAL_API_TOKEN=${token}\n`;
  }
  writeFileSync(envPath, envText);
  env = parseEnv(envText);
  console.log(
    existingDev?.PERSONAL_API_TOKEN === token
      ? 'Copied the existing tracker token into .env'
      : 'Generated a personal API token in .env',
  );
}

if (!existsSync(devVarsPath)) {
  const supabaseUrl = isReal(env.SUPABASE_URL, ['YOUR_PROJECT']) ? env.SUPABASE_URL : '';
  const supabaseKey = isReal(env.SUPABASE_SERVICE_ROLE_KEY, ['your-service-role-key'])
    ? env.SUPABASE_SERVICE_ROLE_KEY
    : '';
  const lines = [
    '# Generated by npm run setup. This file is gitignored.',
    `PERSONAL_API_TOKEN=${env.PERSONAL_API_TOKEN}`,
    '',
    '# Leave Supabase unset to store tracking events in memory.',
    '# They disappear when you stop `npm run tracker`.',
  ];
  lines.push(supabaseUrl ? `SUPABASE_URL=${supabaseUrl}` : '# SUPABASE_URL=');
  lines.push(supabaseKey ? `SUPABASE_SERVICE_ROLE_KEY=${supabaseKey}` : '# SUPABASE_SERVICE_ROLE_KEY=');
  lines.push('');
  writeFileSync(devVarsPath, lines.join('\n'));
  console.log('Created workers/tracker/.dev.vars for the local tracker');
}

const devVars = parseEnv(readFileSync(devVarsPath, 'utf8'));
const token = devVars.PERSONAL_API_TOKEN || env.PERSONAL_API_TOKEN;
if (!token) fail('No PERSONAL_API_TOKEN in .env or workers/tracker/.dev.vars');
const usingSupabase =
  isReal(devVars.SUPABASE_URL, ['YOUR_PROJECT']) &&
  isReal(devVars.SUPABASE_SERVICE_ROLE_KEY, ['your-service-role-key']);

const localDir = join(root, '.local');
mkdirSync(localDir, { recursive: true });
const trackerCard = [
  'Tracker (optional)',
  '',
  'Start:   npm run tracker',
  'URL:     http://127.0.0.1:8787',
  `Token:   ${token}`,
  `Store:   ${usingSupabase ? 'Supabase (kept after you stop the tracker)' : 'memory (cleared when you stop the tracker)'}`,
  '',
  'Extension → Settings → Tracking → paste the URL and token → Save settings.',
  'Skip this if you only want inbox categories, summaries, and Ask Inbox.',
  '',
].join('\n');
writeFileSync(join(localDir, 'tracker.txt'), trackerCard);

console.log('\nBuilding the extension…\n');
if (run('npm', ['run', 'build']) !== 0) {
  fail('Build failed. Fix the error above, then run npm run setup again.');
}

const dist = join(root, 'apps', 'extension', 'dist');
if (!existsSync(join(dist, 'manifest.json'))) {
  fail('Build finished, but apps/extension/dist/manifest.json is missing.');
}

console.log(`
Ready.

Extension folder:
  ${dist}

Load it in Chrome
  1. Open chrome://extensions
  2. Turn on Developer mode (top right)
  3. Click Load unpacked
  4. Select the folder above (the one that contains manifest.json)

Try the inbox
  1. Pin "Gmail Intelligence" from the puzzle-piece menu
  2. Open https://mail.google.com while you are signed in
  3. Click the extension icon
  4. Sign in with ChatGPT, or download a model
     Categories still work if you skip that
  5. Open a thread. A summary sidebar and category labels should show up
  6. If Gmail looks unchanged, open extension Settings and click Run diagnostics

While developing
  npm run dev
  Then click Reload on chrome://extensions after it rebuilds

Tracking (optional)
  npm run tracker
  Paste the URL and token from .local/tracker.txt into Settings → Tracking
  Click Save settings
  ${usingSupabase ? 'This machine is set up to store events in Supabase.' : 'Events stay in memory until you stop the tracker. No cloud account needed.'}

The same steps are in the README under "Install".
`);

if (openAfter) {
  const status = run(process.execPath, [join(root, 'scripts', 'open.mjs')]);
  if (status !== 0) process.exit(status);
}
